import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import { ReactLenis } from "lenis/react";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ['latin'],
})

export const metadata = {
  title: "My Health Prac",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${manrope.className} antialiased  `}
      >
        <ReactLenis root>
          {children}
        </ReactLenis>
      </body>
    </html>
  );
}
